filter_tau: 300 #ns, filtering anode signal gaussian
zero_amplitude_threshold: 1 #if max-sample is less than this, don't integrate
fit_amplitude_threshold: 0.003 #if max-sample is above this, fit the exponential to get tau and amplitude
anode_integration_window: [-100, 500] #us, skip integrating the baseline samples, just integrate this window about peak time.
pmt_integration_window: [0, 85]
rogowski_voltage: 5000 